get https://xc8jbrf4-3000.euw.devtunnels.ms/api/contacts
###
get https://xc8jbrf4-3000.euw.devtunnels.ms/api/contacts/66a02b3679fe5dffdfafc64b
###

POST https://xc8jbrf4-3000.euw.devtunnels.ms/api/contacts
Content-Type: application/json

{
  "name": "Allen Raymond",
  "email": "nulla.ante@vestibul.co.uk",
  "phone": "(992) 914-3792"
}

###
PATCH https://xc8jbrf4-3000.euw.devtunnels.ms/api/contacts/66a69ac23b99ae2818730218
Content-Type: application/json

{
 "name": "Allen Raymond1"
}
###
PATCH https://xc8jbrf4-3000.euw.devtunnels.ms/api/contacts/66a69ac23b99ae2818730218/favorite
Content-Type: application/json

{
 "favorite": true
}
###

DELETE https://xc8jbrf4-3000.euw.devtunnels.ms/api/contacts/66a69ac23b99ae2818730218
###